import type { Metadata } from "next";
import "./globals.css";
import LandingScreen from "./components/LandingPage";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>
          cse-alumni-site
        </title>
      </head>
     <div>
      <LandingScreen></LandingScreen>
     </div>
    </html>
  );
}
